# Generated by Django 3.2.9 on 2022-02-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0002_rename_register_userregister'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userregister',
        ),
    ]
