# Generated by Django 3.2.9 on 2022-02-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0004_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=200)),
                ('vendorname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('rate', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
            ],
        ),
    ]
