# Generated by Django 3.2.9 on 2022-02-09 17:57

from django.db import migrations, models
import use.models


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=use.models.Worker.get_filename),
        ),
    ]
