# Generated by Django 3.2.9 on 2022-02-25 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import use.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('use', '0008_auto_20220210_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=use.models.Workers.get_filename)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('rate', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('availability', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
