# Generated by Django 3.2.9 on 2022-02-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0009_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workers',
            name='user',
        ),
    ]
