# Generated by Django 3.2.9 on 2022-02-27 18:17

from django.db import migrations, models
import django.db.models.deletion
import use.models


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0010_remove_workers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('rate', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=use.models.product.get_filename)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='use.supplier')),
            ],
        ),
    ]
