# Generated by Django 3.2.9 on 2022-02-28 17:31

from django.db import migrations, models
import django.db.models.deletion
import use.models


class Migration(migrations.Migration):

    dependencies = [
        ('use', '0012_auto_20220227_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=use.models.Post.get_filename)),
                ('body', models.CharField(max_length=200)),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='use.supplier')),
                ('worker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='use.worker')),
            ],
        ),
    ]
